export const uiActionTypes = {
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  CHANGE_ALERT_MESSAGE: "CHANGE_ALERT_MESSAGE",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  SHOW_NOTIFICATIONS: "SHOW_NOTIFICATIONS",
  HIDE_NOTIFICATIONS: "HIDE_NOTIFICATIONS",
  SET_CATEGORIES: "SET_CATEGORIES",
};
